const roomTypes = {
    gambling: {
        name: "Gambling Den",
        job: "Pit Boss",
        dailyWage: 8000,
        icon: "gamble",
        imageUrl: "images/gamblingden.jpg",
        cost: 50000, // Decoration cost in currency
        upkeep: 0.015,
        hint: "A place where fortunes are made... or lost.",
    },
    loansharking: {
        name: "Loan Office",
        job: "Debt Collector",
        dailyWage: 10000,
        icon: "loan",
        imageUrl: "images/loanshark.jpg",
        cost: 20000,
        upkeep: 0.005,
        hint: "Only the most desperate come to borrow...",
    },
    druglab: {
        name: "Drug Laboratory",
        job: "Chemist",
        dailyWage: 12000,
        icon: "drugs",
        imageUrl: "images/drugslab.jpg",
        cost: 30000,
        upkeep: 0.025,
        hint: "A shadowy operation...",
    },
    massageparlor: {
        name: "Massage Parlor",
        job: "Practitioner",
        dailyWage: 6000,
        icon: "massage",
        imageUrl: "images/massageparlor.jpg",
        cost: 30000,
        upkeep: 0.01,
        hint: "Unholy dealings of various kinds...",
    },
    evillair: {
        name: "Evil Lair",
        job: "Partner",
        dailyWage: 0,
        icon: "partner",
        imageUrl: "images/evillair.jpg",
        cost: 10000,
        upkeep: 0,
        hint: "The heart of all your dark plans...",
    }
};
